{
 "title": "node-exporter - hardware",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=~\"$node\"},instance)"
    }
   },
   { "name": "kwh", "label": "kW/h price", "query": "0.3" }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\r\n  (\r\n    sum by (instance) (\r\n      increase(node_rapl_package_joules_total{instance=~\"$instance\",job=\"$job\"}[$__range])\r\n    ) / 3.6e6 * 0.3\r\n  )\r\n* on(instance) group_left(nodename)\r\n  max by (instance, nodename) (node_uname_info{job=\"node-exporter\"})\r\n)\r\n",
     "legendFormat": "Cost"
    },
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "I/O"
    },
    {
     "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Irq"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "CPU time spent busy vs idle, split by activity type",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (\r\n  irate(node_cpu_seconds_total{job=\"$job\", mode=\"system\"}[$__rate_interval])\r\n)\r\n*\r\non(instance) group_left(nodename)\r\nmax by(instance,nodename) (node_uname_info{job=\"$job\", nodename=\"$node\"})",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance)(\r\n  irate(node_cpu_seconds_total{job=\"$job\", mode=\"user\"}[$__rate_interval])\r\n)\r\n*\r\non(instance) group_left(nodename)\r\nmax by(instance,nodename)(node_uname_info{job=\"$job\", nodename=\"$node\"})",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance)(\r\n  irate(node_cpu_seconds_total{job=\"$job\", mode=\"iowait\"}[$__rate_interval])\r\n)\r\n* on(instance) group_left(nodename)\r\nmax by(instance,nodename)(node_uname_info{job=\"$job\", nodename=\"$node\"})",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance)(\r\n  irate(node_cpu_seconds_total{job=\"$job\", mode=~\".*irq\"}[$__rate_interval])\r\n)\r\n* on(instance) group_left(nodename)\r\nmax by(instance,nodename)(node_uname_info{job=\"$job\", nodename=\"$node\"})",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance)(\r\n  irate(node_cpu_seconds_total{job=\"$job\",\r\n                               mode!=\"idle\",\r\n                               mode!=\"user\",\r\n                               mode!=\"system\",\r\n                               mode!=\"iowait\",\r\n                               mode!=\"irq\",\r\n                               mode!=\"softirq\"}[$__rate_interval])\r\n)\r\n* on(instance) group_left(nodename)\r\nmax by(instance,nodename)(node_uname_info{job=\"$job\", nodename=\"$node\"})",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance)(\r\n  irate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])\r\n)\r\n* on(instance) group_left(nodename)\r\nmax by(instance,nodename)(node_uname_info{job=\"$job\", nodename=\"$node\"})",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\",node=\"$node\"}) by (instance)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum by(node)(\r\n  kube_pod_container_resource_requests{resource=\"cpu\",unit=\"core\",node=\"$node\"}\r\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(node)(\r\n  kube_pod_container_resource_limits{resource=\"cpu\",unit=\"core\",node=\"$node\"}\r\n)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Per-interface network traffic (receive and transmit) in bits per second",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max without (pod,container,endpoint,service) (\r\n  rate(node_network_receive_bytes_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])\r\n) * 8\r\n* on(instance) group_left(nodename)\r\n  max by (instance,nodename) (node_uname_info{job=\"$job\",nodename=\"$node\"})\r\n",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "max without (pod,container,endpoint,service) (\r\n  rate(node_network_transmit_bytes_total{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])\r\n) * 8\r\n* on(instance) group_left(nodename)\r\n  max by (instance,nodename) (node_uname_info{job=\"$job\",nodename=\"$node\"})\r\n",
     "legendFormat": "Tx {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  (\r\n    (\r\n      max without (pod,container,endpoint,service) (\r\n        node_filesystem_size_bytes{instance=~\"$instance\",job=\"$job\",device!~\"rootfs\"}\r\n      )\r\n    -\r\n      max without (pod,container,endpoint,service) (\r\n        node_filesystem_avail_bytes{instance=~\"$instance\",job=\"$job\",device!~\"rootfs\"}\r\n      )\r\n    )\r\n    /\r\n    max without (pod,container,endpoint,service) (\r\n      node_filesystem_size_bytes{instance=~\"$instance\",job=\"$job\",device!~\"rootfs\"}\r\n    )\r\n  ) * 100 != 0\r\n)\r\n* on(instance) group_left(nodename)\r\n  max by (instance,nodename) (node_uname_info{job=\"$job\",nodename=\"$node\"})\r\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Watts and Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(node_hwmon_temp_celsius{instance=~\"$instance\"}) by (instance)\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Temp"
    },
    {
     "expr": "rate(node_rapl_package_joules_total{instance=~\"$instance\"}[$__rate_interval])\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Watts"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "RAM and swap usage overview, including caches",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(node_memory_MemTotal_bytes{job=\"$job\"})\r\n*\r\non(instance) group_left(nodename)\r\nmax by(instance,nodename) (node_uname_info{job=\"$job\",nodename=\"$node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (instance) (\r\n  node_memory_MemTotal_bytes{job=\"$job\"} \r\n  - node_memory_MemFree_bytes{job=\"$job\"} \r\n  - (node_memory_Cached_bytes{job=\"$job\"} \r\n  + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_SReclaimable_bytes{job=\"$job\"})\r\n)\r\n*\r\non(instance) group_left(nodename)\r\nmax by(instance,nodename) (node_uname_info{job=\"$job\",nodename=\"$node\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "(  \r\n  node_memory_Cached_bytes{job=\"$job\"} \r\n  + node_memory_Buffers_bytes{job=\"$job\"} \r\n  + node_memory_SReclaimable_bytes{job=\"$job\"}\r\n)\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\"}\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "(\r\n  (node_memory_SwapTotal_bytes{job=\"$job\"} \r\n  - node_memory_SwapFree_bytes{job=\"$job\"})\r\n)\r\n*\r\non(instance) group_left(nodename)\r\nnode_uname_info{job=\"$job\",nodename=\"$node\"}",
     "legendFormat": "Swap used"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=\"$node\"}) by (instance)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum by(node)(\r\n  kube_pod_container_resource_requests{resource=\"memory\",unit=\"byte\",node=\"$node\"}\r\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by(node)(\r\n  kube_pod_container_resource_limits{resource=\"memory\",unit=\"byte\",node=\"$node\"}\r\n)",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}