{
 "title": "Thanos / Overview",
 "description": "This dashboard provides a resource usage overview of the Thanos components Querier, Query-Frontend, Compacter and Store.\r\n\r\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted and the cache hit ratio is available.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://repository-images.githubusercontent.com/109162639/97e49180-661b-11e9-9882-fdc44b74debd)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count\n(\n  kube_pod_container_info{namespace=\"monitoring\",pod=~\"thanos-.*\"}\n) by (container)\n",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "Thanos / Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"monitoring\",container=\"query\"}[$__rate_interval])) by (pod)",
     "legendFormat": "usage: {{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",container=\"query\",resource=\"cpu\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",container=\"query\",resource=\"cpu\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{namespace=\"monitoring\",container=\"query\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",container=\"query\",resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",container=\"query\",resource=\"memory\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"monitoring\",pod=~\"thanos-query-.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Thanos / Query Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Core Usage vs. Requested",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"query-frontend\",pod=~\"thanos.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",container=\"query-frontend\",pod=~\"thanos.*\",resource=\"cpu\"})",
       "legendFormat": "limits"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",container=\"query-frontend\",pod=~\"thanos.*\",resource=\"cpu\"})",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Memory Usage v. Limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"query-frontend.*\",pod=~\"thanos.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",container=~\"query-frontend.*\",pod=~\"thanos.*\",resource=\"memory\"})",
       "legendFormat": "limits"
      },
      {
       "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",container=~\"query-frontend.*\",pod=~\"thanos.*\",resource=\"memory\"})",
       "legendFormat": "requests"
      }
     ]
    },
    {
     "title": "Last Terminated Reason",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-query-frontend.*\"} != 0",
       "legendFormat": "{{reason}} - {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thanos / Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\",container=\"storegateway\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\",container=\"storegateway\",resource=\"cpu\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\",container=\"storegateway\",resource=\"cpu\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\",container=\"storegateway\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\",container=\"storegateway\",resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\",container=\"storegateway\",resource=\"memory\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"monitoring\",pod=~\"thanos-storegateway-.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    thanos_store_index_cache_hits_total[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    thanos_store_index_cache_requests_total[$__rate_interval]\n  ) \n)",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(thanos_store_index_cache_hits_total[5m])",
     "legendFormat": "{{item_type}} - {{pod}}"
    }
   ]
  },
  {
   "title": "bucket_store_cached_series_fetch_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(thanos_bucket_store_cached_series_fetch_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Thanos / Compact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",container=\"compactor\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",container=\"compactor\",resource=\"cpu\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",container=\"compactor\",resource=\"cpu\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",container=\"compactor\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",container=\"compactor\",resource=\"memory\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",container=\"compactor\",resource=\"memory\"})",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"monitoring\",pod=~\"thanos-compactor-.*\",} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  }
 ]
}