{
 "title": "Speedtest",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_speed_bps", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_ms", "legendFormat": "{{cluster}}" }
   ]
  },
  {
   "title": "Speedtest histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster)(download_speed_bps)",
     "legendFormat": "{{cluster}} - download"
    },
    {
     "expr": "sum by (cluster)(upload_speed_bps)",
     "legendFormat": "{{cluster}} - upload"
    },
    { "expr": "sum by (cluster)(ping_ms)", "legendFormat": "{{cluster}} - ping" }
   ]
  }
 ]
}