{
 "title": "OTel Collector Simple",
 "tags": [ "OTel" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total,job)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total,cluster)"
    }
   },
   {
    "name": "otel_signal",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{cluster=~\"$cluster\"},otel_signal)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{job=~\"$job\", cluster=~\"$cluster\", otel_signal=~\"$otel_signal\"},pod)"
    }
   },
   { "name": "minsteps", "label": "interval", "query": "10s,30s,1m,5m,15m,30m" },
   {
    "name": "grouping",
    "label": "Additional groupping",
    "query": "None :  , By transport : \\,transport\\,cluster, By cluster : \\,cluster, By pod : \\,cluster\\,pod"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Instances Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(otelcol_process_cpu_seconds_total{cluster=~\"$cluster\",job=\"$job\",otel_signal=~\"$otel_signal\"})"
    }
   ]
  },
  {
   "title": "OTEL Instances Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "otelcol_process_uptime_seconds_total{job=~\"$job\",otel_signal=~\"$otel_signal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (rate(otelcol_process_cpu_seconds_total{cluster=~\"$cluster\",job=\"$job\",pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (otelcol_process_memory_rss_bytes{cluster=~\"$cluster\",job=\"$job\",pod=~\"$pod\",otel_signal=~\"$otel_signal\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (otelcol_process_cpu_seconds_total{cluster=~\"$cluster\",job=\"$job\",otel_signal=~\"$otel_signal\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Instance resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_process_cpu_seconds_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval]))  by (job $grouping) ",
     "legendFormat": "{{job}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(otelcol_process_memory_rss_bytes{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}) by (job $grouping)",
     "legendFormat": "rss {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(otelcol_process_runtime_heap_alloc_bytes{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}) by (job $grouping)",
     "legendFormat": "heap {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(otelcol_process_runtime_total_sys_memory_bytes{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}) by (job $grouping)",
     "legendFormat": "total {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "exporter queue (batches)",
   "type": "timeseries",
   "description": "if the queue limit is reached, accepted spans will be dropped",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_queue_capacity{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}) by (exporter $grouping)",
     "legendFormat": "capacity: {{exporter}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(otelcol_exporter_queue_size{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}) by (exporter $grouping)",
     "legendFormat": "size: {{exporter}} {{cluster}} {{pod}}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "receiver metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{cluster=~\"$cluster\",job=\"$job\",pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval]))  by (receiver $grouping) ",
     "legendFormat": "accepted: {{receiver}} {{cluster}} {{pod}} "
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (receiver $grouping) ",
     "legendFormat": "refused: {{receiver}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "processor metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_metric_points_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping) ",
     "legendFormat": "accepted: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_metric_points_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "dropped: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_metric_points_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "refused: {{processor}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "exporter metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{cluster=~\"$cluster\",job=\"$job\",pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "success: {{exporter}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "failed: {{exporter}} {{cluster}} {{pod}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "receiver logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_log_records_total{cluster=~\"$cluster\",job=\"$job\",pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (receiver $grouping) ",
     "legendFormat": "accepted: {{receiver}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (receiver $grouping) ",
     "legendFormat": "refused: {{receiver}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_receiver_failed_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (receiver $grouping) ",
     "legendFormat": "failed: {{receiver}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "processor logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping) ",
     "legendFormat": "accepted: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping) ",
     "legendFormat": "dropped: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_inserted_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping) ",
     "legendFormat": "refused: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping) ",
     "legendFormat": "refused: {{processor}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "exporter logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_log_records_total{cluster=~\"$cluster\",job=\"$job\",pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (exporter $grouping) ",
     "legendFormat": "success: {{exporter}} {{cluster}} {{pod}} "
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_log_records_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "failed: {{exporter}} {{cluster}} {{pod}}"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "receiver spans/s",
   "type": "timeseries",
   "description": "accepted: the application was able to submit the span",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "accepted: {{receiver}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "refused: {{receiver}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "processor spans/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval]))  by (processor $grouping)",
     "legendFormat": "accepted: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "refused: {{processor}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans_total{job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (processor $grouping)",
     "legendFormat": "dropped: {{processor}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "exporter spans/s",
   "type": "timeseries",
   "description": "failed exports most likely indicate issues with one of the backends",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total{cluster=~\"$cluster\",job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "success: {{exporter}} {{cluster}} {{pod}}"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans_total{job=\"$job\", pod=~\"$pod\",otel_signal=~\"$otel_signal\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "failed: {{exporter}} {{cluster}} {{pod}}"
    }
   ]
  },
  {
   "title": "compliance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "otel instances without otel_signal label",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 47 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(otelcol_process_cpu_seconds_total{cluster=~\".+\",job=\"otelcol-contrib\",otel_signal=\"\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}