{
 "title": "Prometheus Overview",
 "description": "Based on https://grafana.com/grafana/dashboards/3662-prometheus-2-0-overview/",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values({job=~\".+prometheus.+\", container=\"prometheus\"},job)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(up{job=\"$job\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "at a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Percentage of uptime during the period ${__from:date} - ${__to:date}.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  avg_over_time(\r\n    up{\r\n      job=~\"$job\",\r\n      service=~\"$service\",\r\n      container=\"prometheus\"\r\n    }[$__range]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Down",
   "type": "table",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{job=~\"$job\", service=~\"$service\"} < 1"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"$job\", service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "quick numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prometheus_build_info) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Tardy Scrapes",
   "type": "stat",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",service=~\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Reload Failures",
   "type": "stat",
   "description": "Number of times the database failed to reload block data from disk.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=~\"$job\",service=~\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Skipped Scrapes",
   "type": "stat",
   "description": "Sum of all skipped scrapes",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",service=~\"$service\"}[$__range])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",service=~\"$service\"}[$__range])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",service=~\"$service\"}[$__range])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",service=~\"$service\"}[$__range])) "
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Failures and Errors",
   "type": "timeseries",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_missed_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_evaluator_iterations_skipped_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Skipped Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "Reload"
    }
   ]
  },
  {
   "title": "up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upness (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\", service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Series Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\", service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_created_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval]) )",
     "legendFormat": "created"
    },
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval]) )",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "appended samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Appended Samples per Second",
   "type": "timeseries",
   "description": "Rate of total number of appended samples",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\", service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape Sync Total",
   "type": "timeseries",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_sync_total{job=~\"$job\", service=~\"$service\"}) by (scrape_job)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) by (scrape_job) * 1000",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "scrapes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\", service=~\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "timeseries",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\", service=~\"$service\"})",
     "legendFormat": "exceeded sample limit"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\", service=~\"$service\"})",
     "legendFormat": "duplicate timestamp"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\", service=~\"$service\"})",
     "legendFormat": "out of bounds"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\", service=~\"$service\"}) ",
     "legendFormat": "out of order"
    }
   ]
  },
  {
   "title": "durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=~\"$job\", service=~\"$service\"}) by (slice)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Notifications Sent",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_notifications_sent_total[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minutes Since Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$job\", service=~\"$service\"}) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=~\"$job\", service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"$job\", service=~\"$service\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}